services:
  # PostgreSQL Database
  - type: pserv
    name: os-manager-postgres
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile.postgres
    envVars:
      - key: POSTGRES_DB
        value: docker_os_manager
      - key: POSTGRES_USER
        value: admin
      - key: POSTGRES_PASSWORD
        generateValue: true

  # Redis Cache
  - type: redis
    name: os-manager-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  # Main Application (Backend + Frontend)
  - type: web
    name: os-manager-app
    env: node
    plan: starter
    buildCommand: npm run install-all && cd server && npm run build && cd ../client && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromService:
          type: pserv
          name: os-manager-postgres
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: os-manager-postgres
          property: port
      - key: DB_NAME
        value: docker_os_manager
      - key: DB_USER
        value: admin
      - key: DB_PASSWORD
        generateValue: true
      - key: REDIS_HOST
        fromService:
          type: redis
          name: os-manager-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: os-manager-redis
          property: port
    healthCheckPath: /api/health

  # Ubuntu Linux Desktop with noVNC
  - type: pserv
    name: ubuntu-desktop
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile.ubuntu
    envVars:
      - key: VNC_PASSWORD
        value: osmanager
      - key: RESOLUTION
        value: 1920x1080

  # Alpine Linux Desktop with VNC
  - type: pserv
    name: alpine-desktop
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile.alpine
    envVars:
      - key: VNC_PASSWORD
        value: osmanager
      - key: RESOLUTION
        value: 1920x1080

  # Debian Linux Desktop with XFCE
  - type: pserv
    name: debian-desktop
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile.debian
    envVars:
      - key: VNC_PW
        value: osmanager
      - key: VNC_RESOLUTION
        value: 1920x1080
