apiVersion: v1
kind: Secret
metadata:
  name: {{APP_NAME}}-secrets
  namespace: {{NAMESPACE}}
type: Opaque
data:
  # Base64 encoded values
  # Default: admin (YWRtaW4=), password (cGFzc3dvcmQ=)
  # Change these values for production!
  db-user: YWRtaW4=
  db-password: cGFzc3dvcmQ=