apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-service
  namespace: {{NAMESPACE}}
  labels:
    app: {{APP_NAME}}
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
    protocol: TCP
    name: http
  selector:
    app: {{APP_NAME}}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{NAMESPACE}}
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: {{NAMESPACE}}
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis---

apiVersion: v1
kind: Service
metadata:
  name: ubuntu-desktop-service
  namespace: {{NAMESPACE}}
  labels:
    app: ubuntu-desktop
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
    protocol: TCP
    name: vnc
  selector:
    app: ubuntu-desktop
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-desktop-service
  namespace: {{NAMESPACE}}
  labels:
    app: alpine-desktop
spec:
  type: NodePort
  ports:
  - port: 6080
    targetPort: 6080
    nodePort: 30001
    protocol: TCP
    name: vnc
  selector:
    app: alpine-desktop
---
apiVersion: v1
kind: Service
metadata:
  name: debian-desktop-service
  namespace: {{NAMESPACE}}
  labels:
    app: debian-desktop
spec:
  type: NodePort
  ports:
  - port: 5901
    targetPort: 5901
    nodePort: 30003
    protocol: TCP
    name: vnc
  selector:
    app: debian-desktop